### ISSUE TITLE
More levels needed!

### ISSUE THREAD

**Issue by Exxili** [techdude101/covid-space-invaders#1]
![image](https://user-images.githubusercontent.com/32906176/129622478-dcce7396-ebaa-4b0c-9afd-f6125c3a268f.png)

**Comment by techdude101** [comment]
Thanks for the suggestion of adding more levels.
Added 10 more levels.

**Comment by Exxili** [comment]
@techdude101 Mark mate,  Its Andy,  any chance i can message you somewhere for a quick chat?

**Comment by techdude101** [comment]
Give me a shout on LinkedIn
https://www.linkedin.com/in/mark-mckee/

**Comment by Exxili** [comment]
@techdude101 connected
